services:
  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: bloglist-reverse-proxy
    depends_on:
      - app
      - server

  app:
    image: bloglist-front
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: bloglist-front

  server:
    image: bloglist-backend
    build:
      context: backend/
      dockerfile: Dockerfile
    container_name: bloglist-backend
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGODB_URI=${MONGODB_URI}
      - SECRET=${SECRET}
    depends_on:
      - redis

  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data

volumes:
  redis_data:
